### ISSUE TITLE
Using ALS as a language server needs updating

### ISSUE THREAD

**Issue by ryan-slack-big** [aml-org/als#502]
The  instructions in the readme for [Using ALS as a language server](https://github.com/aml-org/als#using-als-as-a-language-server) don't work. It would appear `als-server.3.x.x.jar` is not built as an assembly so won't easily run as a jar. At the same time, `api-language-server_2.12-3.2.5-1.jar`  lacks a main entry in the manifest for `org.mulesoft.als.server.lsp4j.Main`, but otherwise seems to work.

**Comment by llibarona** [comment]
Hi @ryan-slack-big !
Have you tried `https://github.com/aml-org/als/blob/develop/documentation/CONTRIBUTING.md` way of assembling the `jar`?
Using sbt, you can assemble the asset by using `sbt -mem 4000 serverJVM/assembly` (memory is recommended) which should generate the artifact.
We will look at the published `jars` to fix this issues you mention, thanks for bringing them to our attention

**Comment by agusayerza** [comment]
Hey @ryan-slack-big,
We will update documentation accordingly to make this clear. In the mean time you can assemble the jar as @llibarona mentioned. Closing the issue for now, don't hesitate to let us know if the assembly does not solve it for you.
