### ISSUE TITLE
Language server stops responding to requests

### ISSUE THREAD

**Issue by deiteris** [aml-org/als#504]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
    - [x] bug report
    - [ ] feature request
    - [ ] question
    - [ ] other

* **What is the current behavior?**

The language server stops responding to language client requests at some point, causing the language client to misbehave as well. The issue mainly happens when actively typing.

* **If the current behavior is a bug, please provide the minimal steps to reproduce on ALS**

The quickest way to reproduce it is:

1. Open any RAML document.
2. Start creating a new object type with multiple nested objects with the help of autocomplete.

* **Please provide stack traces/logs and the failing JSON rpc message if possible**

Here's the full trace: [trace.zip](https://github.com/aml-org/als/files/6285981/trace.zip). The server stops responding once the client starts sending `$/cancelRequest` notifications.

* **File being edited (API spec/AML Document)**

Any RAML file.

* **Please tell us about your environment:**

    - ALS Version: 3.3.0-SNAPSHOT
    - ALS Distribution: JVM
    - OS: Windows 10 20H2

**Comment by deiteris** [comment]
So, I've been observing the issue, learned a bit of Scala and more VS Code LSP API and figured out that it must be `onDidChangeTextDocument` which causes the issue. In ALS implementation I found the method https://github.com/aml-org/als/blob/develop/als-server/shared/src/main/scala/org/mulesoft/als/server/textsync/TextDocumentManager.scala#L90, and I noticed that it doesn't implement requests throttling, and it means that I'm simply request-bombing the server with each character I type (and if I type fast enough, the issue happens).

I'm testing a simple request drop if the time between requests is too short (which is not ideal, sometimes I stop typing and validation doesn't happen, but at least it stabilizes the extension), and everything seems to be stable even if I'm just randomly pressing all keys at the same time:
```
  override def didChange(params: DidChangeTextDocumentParams): Unit = {
    val currentRequestTime = System.currentTimeMillis
    val timeDiff = currentRequestTime - this.prevRequestTime
    if (currentRequestTime - this.prevRequestTime > 500) {
      this.prevRequestTime = currentRequestTime
      val document = params.textDocument
      val version  = document.version.getOrElse(0)
      val text     = params.contentChanges.headOption.map(_.text)

      documentWasChanged(ChangedDocument(document.uri.toAmfUri, version, text, None))
    }
  }
```

**Comment by deiteris** [comment]
Ok, I've no idea how to explain this, but assigning the process to a variable somehow **fixes** it. I was following the tutorial and did the same, but I had no idea why the variable was declared, but not used so I removed it.
```js
const process = child_process.spawn("java", args, options)
```

**Comment by deiteris** [comment]
Apparently, this is somehow related to nodejs. When I attach an event listener on the ALS process to see what happens, I am unable to reproduce the issue...
```
const process = child_process.spawn("java", args, options)
process.stdout.on('data', data => console.log(data.toString()))
```

**Comment by deiteris** [comment]
So, quick summary:

1. The issue is not related to ALS.
2. The issue also cannot be reproduced if ALS is opened in `cmd` and attached to port.

Either an issue with Windows stdout or in node. Attaching an empty event listener on stdout works for me:
```js
// eslint-disable-next-line @typescript-eslint/no-empty-function
process.stdout.on('data', (data: any) => { })
```

Thus, closing the issue.

**Comment by agusayerza** [comment]
Hey @deiteris,

Thanks for the report and the gathered data. We will try and take a look to find if there is anything we can do about it.
