### ISSUE TITLE
The "fileUsage" method always returns empty array

### ISSUE THREAD

**Issue by deiteris** [aml-org/als#508]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
    - [x] bug report
    - [ ] feature request
    - [ ] question
    - [ ] other

* **What is the current behavior?**

When sending a request with the "fileUsage" method, it always returns an empty array, even though the file is used in other file.

* **If the current behavior is a bug, please provide the minimal steps to reproduce on ALS**

Here's the test project: [test.zip](https://github.com/aml-org/als/files/6313599/test.zip)
You can see that all files are linked to `api.raml`, but none of them returns reference locations.

* **Please provide stack traces/logs and the failing JSON rpc message if possible**

Full trace: https://pastebin.com/AXLHSz5h

* **File being edited (API spec/AML Document)**

See the test project in current behavior.

* **What is the expected behavior?**

An array of locations, containing the uri of `api.raml`.

* **What is the motivation/use case for changing the behavior? (for feature requests)**

* **Please tell us about your environment:**

    - ALS Version: 3.3.0-SNAPSHOT
    - ALS Distribution: JVM
    - OS: Windows 10 20H2

* **Other information** (e.g. detailed explanation, stack traces, related issues, workarounds, links for us to have context, eg. StackOverflow, Gitter, etc)

**Comment by agusayerza** [comment]
Hey @deiteris,

This behaviour is the expected one. Some actions such as `fileUsage` are only implemented for what we call _projects_. A _project_ is a _workspace_ that has a defined main file, that file an every file referenced from this files or referenced files are part of a tree. In short a project is loosely coupled to a workspace, as any project belongs to a workspace and a workspace can only contain **one** project (but **may** contain none)

Right now the only way to create a project is by creating a file named "exchange.json" and having inside: `{"main":"api.raml"}` where `api.raml` is the main file from which the tree will be created. **Please not this method will probably be changing soon.**

We will be adding documentation to further explain this concepts and clarify for which actions a project is required in order for them to work, but in the mean time the reported issue is not a bug.

**Comment by deiteris** [comment]
Hi @agusayerza 

> This behaviour is the expected one. Some actions such as `fileUsage` are only implemented for what we call _projects_. A _project_ is a _workspace_ that has a defined main file, that file an every file referenced from this files or referenced files are part of a tree. In short a project is loosely coupled to a workspace, as any project must belong to a workspace and any given workspace can only contain **one** project (but **may** contain none)
> 
> Right now the only way to create a project is by creating a file named "exchange.json" and having inside: `{"main":"api.raml"}` where `api.raml` is the main file from which the tree will be created. **Please not this method will probably be changing soon.**
> 
> We will be adding documentation to further explain this concepts and clarify for which actions a project is required in order for them to work, but in the mean time the reported issue is not a bug.

That's what I was also thinking about and thought about implementing this myself, but saw no means to do that from the client side :) Can you tell a bit more about the "exchange.json" file? Is it possible to do it now and how can I provide it to the ALS to use this feature?

**Comment by agusayerza** [comment]
Great to hear it's working for you. Have you tried to do a `fileUsage` request in a project yet? It should work

**Comment by deiteris** [comment]
> Great to hear it's working for you. Have you tried to do a `fileUsage` request in a project yet? It should work

Yes, with the main API file set, `fileUsage` works as well, and the links in separate JSON schemas are working too now.
