### ISSUE TITLE
How to use conversion feature?

### ISSUE THREAD

**Issue by deiteris** [aml-org/als#519]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
    - [ ] bug report
    - [ ] feature request
    - [x] question
    - [ ] other

* **What is the current behavior?**

According to the documentation, I should send a "Conversion" request with an object containing the `uri` key and one of supported conversion formats in the `target` key.

Here's what I do:
```js
const document = window.activeTextEditor?.document
if (document) {
    const uri = client.code2ProtocolConverter.asUri(document.uri)
    const data = await client.sendRequest('conversion', {uri, target: 'OAS 3.0'})
    console.log(data)
}
```

When the conversion is successful, I should receive a list of URIs with converted documents:
```
[
  {
    "uri": "string",
    "document": "string"
  }
]
```

But got:
```
{
    "uri": "file:///e:/Sources/raml-examples/api.raml",
    "content": "file:///e:/Sources/raml-examples/api.raml"
}
```

* **Please provide stack traces/logs and the failing JSON rpc message if possible**

Full trace: https://pastebin.com/ftWcbju6

* **File being edited (API spec/AML Document)**

https://pastebin.com/KyrYaX8e

* **Please tell us about your environment:**

    - ALS Version: 3.3.0-SNAPSHOT
    - ALS Distribution: JVM
    - OS: Windows 10 20H2

**Comment by llibarona** [comment]
Your implementation is correct, we have a wrong conversion in JVM resulting in `content` being sent with the URI instead of the actual content, I will fix this immediatly (`gh-519/serialized-jvm-fix` if you want to try it out)
There is also a difference between pairs (JS/JVM) in which we have different names for the property (thus the wrong documentation), we will fix this in the next major release as it is a change in our default behaviour, but we will document it in the mean time
please let me know if this branch fixes your problems and if there is anything else I can do for you

**Comment by deiteris** [comment]
There are two tests that have failed during the build, one of them is related to RAML 1.0 to OAS 2.0 json conversion https://pastebin.com/g3ppdM6T

I've ignored them and built the binary anyway, now the response is the one I would expect:
```json
{
    "uri": "file:///e:/Sources/raml-examples/api.raml",
    "content": "openapi: 3.0.0\ninfo:\n  title: Example API\n  version: \"1.0\"\nservers:\n  -\n    url: https://example.com\npaths: {}\n"
}
```

**Comment by llibarona** [comment]
> There are two tests that have failed during the build, one of them is "OAS 2.0 to RAML 1.0 json syntax conversion test" https://pastebin.com/g3ppdM6T

I think those tests are not related to this change, we are in the midst of adopting a few changes from our dependencies and our build is inconsistent (it should be fixed briefly)

> I've ignored them and built the binary anyway, now the response is the one I would expect. Thanks!

Great! if there is anything else we can help you with, don't hesitate to let us know!

**Comment by deiteris** [comment]
@llibarona, I noticed that this fix was not applied to the 3.2.8 release. I'll reopen the issue so it won't be lost and you can track it in Jira issue if necessary.

**Comment by llibarona** [comment]
@deiteris  thanks for the remainder,
the idea was to add this to ALS 4.0.0 along with the fixes in pair differences (JVM/JS), but this version is taking a bit longer than expected, so I will see to merge the provisory fix in the mean time

**Comment by llibarona** [comment]
Hi @deiteris , this fix should be in the branch `develop` already, internal ticket [https://www.mulesoft.org/jira/browse/ALS-1482]
Thanks again for the reminder and sorry for the inconveniece!
