### ISSUE TITLE
StringIndexOutOfBoundsException when a type starts with a hashtag

### ISSUE THREAD

**Issue by deiteris** [aml-org/als#523]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
    - [x] bug report
    - [ ] feature request
    - [ ] question
    - [ ] other

* **What is the current behavior?**

When creating an empty type and defining it's type like `type: #` instead of actual RAML type, this triggers StringIndexOutOfBoundsException.

* **If the current behavior is a bug, please provide the minimal steps to reproduce on ALS**

1. Create a RAML document and start describing a new type.
2. Define `type: #` for the type.
3. See the exception in the server trace.

The resulting example should look like this:
```yaml
#%RAML 1.0

title: Sample API

types:
  TestType: #
```

* **Please provide stack traces/logs and the failing JSON rpc message if possible**

Full trace: https://pastebin.com/tDWxHSYC

* **What is the expected behavior?**

Exception should not be triggered in this case.

* **Please tell us about your environment:**

    - ALS Version: 3.2.6
    - ALS Distribution: JVM
    - OS: Windows 10 20H2
    - IDE: Visual Studio Code 1.55.2

* **Other information** (e.g. detailed explanation, stack traces, related issues, workarounds, links for us to have context, eg. StackOverflow, Gitter, etc)

**Comment by llibarona** [comment]
Hi @deiteris 
Unfortunately tomorrows release will still have this bug, but the release after that should have this fixed.
You can try this in `ALS-1233/finder-refactor` branch which is in final stages of review before merging to `develop` (this involves plenty of core changes which should fix some minor issues like this and help us improve others)
Please let me know if there is anything else I can help you with.
And thanks for your continuos reports!

**Comment by llibarona** [comment]
link to internal ticket: https://www.mulesoft.org/jira/browse/ALS-1487

**Comment by deiteris** [comment]
Hi @llibarona,

Ok, I can live with that :) Good luck with your next release!

**Comment by llibarona** [comment]
Thanks very much!! We hope this next one is quiet, but the one after that is a tough one 😆 
Probably 4.0.0 (so we include the changes you reported with differences between JS and JVM pairs)
