### ISSUE TITLE
Defining a library with relative path starting with "." triggers CompletionException

### ISSUE THREAD

**Issue by deiteris** [aml-org/als#533]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
    - [x] bug report
    - [ ] feature request
    - [ ] question
    - [ ] other

* **What is the current behavior?**

When defining a library and starting its path with a dot, the language server throws java.util.concurrent.CompletionException.

* **If the current behavior is a bug, please provide the minimal steps to reproduce on ALS**

Create a RAML document and try to define a library path starting with a dot:
```yaml
#%RAML 1.0

title: ACME Banking HTTP API
version: 1.0
mediaType: application/json

uses:
  myLib: .
```

* **Please provide stack traces/logs and the failing JSON rpc message if possible**

Here's a full trace:

https://pastebin.com/ZEqggpMk

* **What is the expected behavior?**

There should be no exception, as it doesn't happen with other types of fragments that use `!include`.

* **Please tell us about your environment:**

    - ALS Version: 3.2.7 and 3.3.0-SNAPSHOT
    - ALS Distribution: JVM
    - OS: Windows 10 20H2

**Comment by llibarona** [comment]
Hi there
I created internal this ticket: https://www.mulesoft.org/jira/browse/ALS-1493
so we can estimate and prioritise this bug
I also tagged this github ticket so we can keep you up to date when we fixed this issue!
