### ISSUE TITLE
Fragments resolving issues with als-node-client on Windows

### ISSUE THREAD

**Issue by deiteris** [aml-org/als#567]
* **I'm submitting a ...**
    - [x] bug report
    - [ ] feature request
    - [ ] question
    - [ ] other

* **What is the current behavior?**

I noticed that your VS Code extension is running on NodeJS client so I gave it a try. However, I see additional drive letter in error messages when any fragments are included.
![image](https://user-images.githubusercontent.com/6103913/124434311-67145100-dd7c-11eb-8616-db3783a54d64.png)

* **If the current behavior is a bug, please provide the minimal steps to reproduce on ALS**

Open any RAML document containing includes on Windows.

* **Please provide stack traces/logs and the failing JSON rpc message if possible**

Trace: https://pastebin.com/9MeNKvVU

* **File being edited (API spec/AML Document)**

Any RAML document.

* **Please tell us about your environment:**

    - ALS Version: 3.2.9
    - ALS Distribution: JS
    - OS: Windows 10 21H1

**Comment by llibarona** [comment]
Hi @deiteris !
would you be so kind to upload a simple case with this issue? (mainly to know if this API should be valid itself, or if it is invalid and the only problem is the actual error message)
Thanks!

(internal ticket: https://www.mulesoft.org/jira/browse/ALS-1595)

**Comment by deiteris** [comment]
Hi @llibarona! Sure, here's the example I was using: https://github.com/raml-org/raml-examples/tree/master/schemas. I have no such problem with JVM version of ALS in the same project.

**Comment by llibarona** [comment]
I copied the example and got no error:
![image](https://user-images.githubusercontent.com/45210281/124671655-302d6080-de8c-11eb-9fa9-b9fbaaf23d91.png)

In case of writing an invalid file I do get the report with the wrong path (double drive letter)
![image](https://user-images.githubusercontent.com/45210281/124671749-56530080-de8c-11eb-90ff-0f3547bdcb49.png)

Is it possible you had `person.json` not defined locally? or is there any other step I may have missed to reproduce it?

If the only error is in the report message, I will report the ticket to the corresponding team, but I don't think it will have much priority

**Comment by deiteris** [comment]
I see that you're using 0.1.0-SNAPSHOT, while I'm using v0.3.130 from the market.

Here you can see that I have the file in the same folder, but the error occurs:
![image](https://user-images.githubusercontent.com/6103913/124716732-12eca680-df0d-11eb-832c-8d3c4c1f9782.png)

The extension:
![image](https://user-images.githubusercontent.com/6103913/124714084-fdc24880-df09-11eb-9f39-d8d74542724b.png)

But the thing is that I was also reproduce it in my own plugin by using the compiled `als-node-client` (branches `release/v3.2.9` and `lsp-3.16.0`):
![image](https://user-images.githubusercontent.com/6103913/124716612-f5b7d800-df0c-11eb-9653-4490d4c947a5.png)

If I copy the link without the additional drive letter - the file opens, so the file path is correct.

**Comment by llibarona** [comment]
Great, I could reproduce it
If I open the fragment and then the main file it recognizes it correctly, but if I only open the main file I get the same error
I will look up to it

**Comment by llibarona** [comment]
Hi @deiteris 
The changes regarding this issue should be solved in develop
Please let us know any other inconvenience you may have!
