### ISSUE TITLE
Could we talk with you? 

### ISSUE THREAD

**Issue by eduardo-rubio** [aml-org/als#597]
Hi @deiteris, 
I work with Lucas @BlockLucas in MuleSoft. 
His team owns the VSCode Extension AML Support (https://marketplace.visualstudio.com/items?itemName=MuleSoftInc.aml-vscode) based on ALS like your VSCode extension (https://marketplace.visualstudio.com/items?itemName=deiteris.vs-api-contractor).

We thank your collaborations in our projects and your interest on ALS.

I would like to talk with you and our Product Manager @jstoiko to see how we can work together and concentrate our effort to build an unique VSCode Extension. 

Please let me know if you are interested in talking about that.
Regards, Edu.

**Comment by deiteris** [comment]
Hello @eduardo-rubio,

Thank you for your interest to my extension.

Sure we can talk about this. I am always open for conversation especially if it involves improving existing tooling :)

**Comment by eduardo-rubio** [comment]
Hi @deiteris,
Could you please contact me by mail? My email is eduardo.rubio@mulesoft.com.

Thanks! Edu.
