### ISSUE TITLE
[NodeJS] textDocument requests error: failed with message: Cannot read property 'length' of undefined (-32603).

### ISSUE THREAD

**Issue by deiteris** [aml-org/als#610]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
    - [x] bug report
    - [ ] feature request
    - [ ] question
    - [ ] other

* **If the current behavior is a bug, please provide the minimal steps to reproduce on ALS**

When moving a cursor inside library links, typing some text that is not a valid RAML yet, VS Code shows that requests have failed.
I was able to track down the issue with javascript debugger, 
![image](https://user-images.githubusercontent.com/6103913/132758078-1e51e244-80ff-4b7b-b4b9-4ed62ffce60a.png)

I did a simple workaround in minified file just to make it work by assigning an empty array, in case the left hand side value is undefined, but I didn't research where this issue appears in Scala code.
![image](https://user-images.githubusercontent.com/6103913/132758236-318548ff-8442-45dd-bcd2-af6de3cb3d65.png)

* **Please provide stack traces/logs and the failing JSON rpc message if possible**

Stack trace: https://pastebin.com/09uY1HVz

* **File being edited (API spec/AML Document)**

Any RAML file.

* **What is the expected behavior?**

This shouldn't happen :)

* **Please tell us about your environment:**

    - ALS Version: 4.1.0
    - ALS Distribution: JS
    - OS: Windows 10 21H1
    - Link to your project: https://github.com/deiteris/api-contractor/tree/adopt-node-client-js

* **Other information** (e.g. detailed explanation, stack traces, related issues, workarounds, links for us to have context, eg. StackOverflow, Gitter, etc)

On the side note (completely unrelated to the issue), if you have any communication with the team that develops AML support plugin for VS Code, here's my couple of recommendations:
1. They can adjust webpack config to minify `node_modules` so the extension size will be much smaller (and exclude unnecessary files too).
2. They can remove external dependency on node.js by creating a fork process that will run within VS Code instance, instead of spawning external `node` process.

**Comment by llibarona** [comment]
Hi!
I already passed your tips to the AMF/AML team
regarding this issue, this is occurring solely on the JS asset, is this correct? or have you not tried JVM asset so it may also happen

I cannot reproduce the error, but I probably didn't understand correctly the situation

I have let's say _api.raml_
```
#%RAML 1.0
uses:
  l: lib.raml
```

and _lib.raml_
```
#%RAML 1.0 Library
xyz
```

if I move around any of those files I don't see the mentioned error, is there something different I should be trying?

**Comment by llibarona** [comment]
Having a closer look to the minified code which you edited, I see the array which is giving trouble seems to be the _related information_
If this is the case, then could you provide me with information about wether you are using a project (main file) or not?
thanks!

**Comment by deiteris** [comment]
Here's the gif that shows the issue.
![issue](https://user-images.githubusercontent.com/6103913/132761960-8f38ed57-47d5-4b35-946f-0b9c1875900c.gif)

>If this is the case, then could you provide me with information about wether you are using a project (main file) or not?

Yes, I used the main file (you can see it on the gif), but I've just rechecked with the main file not set, and the issue persists.

**Comment by llibarona** [comment]
Okey, I cannot reproduce the error locally, but according to the logs it fails in a CodeAction, but if setting an empty array in RelatedInformation fixed it then I can make an educated guess and assume the problem is we are not handling `RelatedInformation` as an optional and it is passed through `context` in the `CodeAction` Request, which results in us exploding when this is not found


I sketched a provisory fix here: https://github.com/aml-org/als/tree/GH-610/relatedInformationChange-js

If you want to take a look and are able to check if this works, I will create a story to bring this fix to the main development branch for later releases
I'm sorry I cannot publish a version for you, we are still working on creating our public npm publication pipeline

**Comment by deiteris** [comment]
Yup, this fixes the issue. 

By the way, is it possible to skip minification process during sbt build? That probably would help a lot with debugging. Source maps unfortunately aren't very helpful because some imports are added after the maps are generated, and this makes the mapping incorrect.

>I'm sorry I cannot publish a version for you, we are still working on creating our public npm publication pipeline

That's not urgent, especially if I can build and check myself :)

**Comment by llibarona** [comment]
> Yup, this fixes the issue.
Great! I created ticket [https://www.mulesoft.org/jira/browse/ALS-1696] to remind us to merge this to the development branch and add some additional tests.

> By the way, is it possible to skip minification process during sbt build? That probably would help a lot with debugging. Source maps unfortunately aren't very helpful because some imports are added after the maps are generated, and this makes the mapping incorrect.
I think you should find the non-minified version in `als-node-client/node-package/tmp`,  the configuration is in `build.sbt`, basically the change is from `fastOptJS` to `fullOptJS`, sadly, it is still scala transpiled code which is not a beauty to debug in JS

> That's not urgent, especially if I can build and check myself :)

Great! hopefully for next release we manage to publish in npmjs :D

**Comment by llibarona** [comment]
https://www.mulesoft.org/jira/browse/ALS-1697

I also created a ticket to check on your previous suggestions regarding the extension, thanks!
