### ISSUE TITLE
No document formatting in JS variant

### ISSUE THREAD

**Issue by deiteris** [aml-org/als#641]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
    - [ ] bug report
    - [ ] feature request
    - [x] question
    - [ ] other

* **What is the current behavior?**

I noticed that document formatting is not enabled by default in JS variant. The server is initialized with the following capabilities:
```
[Trace - 11:42:24] Received response 'initialize - (0)' in 1813ms.
Result: {
    "capabilities": {
        ...
        "documentFormattingProvider": false,
        "documentRangeFormattingProvider": false,
        ...
    }
}
```

While in JVM, these capabilities are set to true and formatting works. Do I need to change anything on extension side, or it should be enabled on the server side?

* **Please provide stack traces/logs and the failing JSON rpc message if possible**

[jvm_trace.txt](https://github.com/aml-org/als/files/7424659/jvm_trace.txt)
[js_trace.txt](https://github.com/aml-org/als/files/7424660/js_trace.txt)

* **What is the expected behavior?**

Formatting should work in both variants.

* **Please tell us about your environment:**

    - ALS Version: 4.2.0
    - ALS Distribution: JS
    - OS: Windows 10 21H1

**Comment by llibarona** [comment]
merged un v5.0.0
