### ISSUE TITLE
Failed to compile `als-node-client` from v5.0.0 tag

### ISSUE THREAD

**Issue by deiteris** [aml-org/als#698]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
    - [x] bug report
    - [ ] feature request
    - [ ] question
    - [ ] other

* **What is the current behavior?**
I'm trying to compile the `als-node-client` project from v5.0.0 tag, but failing with the following error:
```
[warn] /home/snek/als/als-node-client/src/main/scala/org/mulesoft/als/nodeclient/Main.scala:9:39: imported `AmfCustomValidatorNode' is permanently hidden by definition of object AmfCustomValidatorNode in package nodeclient
[warn] import amf.validation.internal.unsafe.AmfCustomValidatorNode
[warn]                                       ^
[error] /home/snek/als/als-node-client/src/main/scala/org/mulesoft/als/nodeclient/Main.scala:54:35: type mismatch;
[error]  found   : org.mulesoft.als.nodeclient.AmfCustomValidatorNode.type
[error]  required: amf.validation.client.validator.AmfWasmOpaValidator
[error]             new JsCustomValidator(AmfCustomValidatorNode).validate(document, profile).toJSPromise
[error]                                   ^
[warn] one warning found
[error] one error found

up to date, audited 100 packages in 3s

36 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

up to date, audited 100 packages in 721ms

36 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
[error] (nodeClient / Compile / compileIncremental) Compilation failed
[error] Total time: 9 s, completed Jan 24, 2022, 12:21:38 PM
```

* **What is the expected behavior?**

Build shouldn't fail.

* **Please tell us about your environment:**

    - ALS Version: 5.0.0
    - ALS Distribution: JS
    - OS: Ubuntu 21.04

**Comment by llibarona** [comment]
Hi @deiteris ! 
could you instruct me the steps you take in order to build the client?
thanks!

**Comment by deiteris** [comment]
Hi @llibarona. Yes, I was able to compile all ALS 4 tags without issues previously, but somehow unable to compile ALS 5 tags.

Here're the steps:
1. Clone the repo.
2. Checkout `v5.0.0` tag.
3. Build with the `sbt -J-Xmx4G buildNodeJsClient` command.

I've just checked out the `v5.0.0-2` tag, and it's the same.

**Comment by llibarona** [comment]
Thanks for the info,
I will look into this issue and let you know as soon as I find a fix

**Comment by llibarona** [comment]
Just to be sure, have you tried running `sbt clean` before the build? I think if you come from a previous version there are some compiled assets which generate incompatibilities

**Comment by deiteris** [comment]
Aaaaa, yes. I already had the project compiled from v4.2.2 and didn't try to clean. Sorry for wasting your time, it compiles correctly after running `sbt clean`.

**Comment by llibarona** [comment]
Splendid! no waste of time at all!
If there is anyhing else I can help you with, please let me know!
best regards
