### ISSUE TITLE
AsyncAPI 2.6 support?

### ISSUE THREAD

**Issue by mhanberg** [aml-org/als#896]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
    - [ ] bug report
    - [x] feature request
    - [ ] question
    - [ ] other

I am noticing that there have been 6 releases of AsyncAPI since 2.0, but ALS only supports 2.0.

Are there plans to support newer versions?

**Comment by llibarona** [comment]
Hi @mhanberg!
We try to support every Spec supported by [AMF](https://github.com/aml-org/amf)
The AMF team is currently estimating effort for the different Async and OpenAPI versions support.
It is not yet in the roadmap, but the most optimistic scenario would render it at the end of year (but it will probably be pushed for the next year).

**Comment by mhanberg** [comment]
Very nice, thank you!

**Comment by llibarona** [comment]
You're welcome!
